### ISSUE TITLE
roslaunch: feature request: remap service

### ISSUE THREAD

**Issue by jianghengle** [ros/ros#22] opened 2013-07-05 16:11 UTC
In the documentation, remapping only works for topic and parameter. I don't know if  there is some particular reason not to remapping service. If not, could we have the feature in the future?

**Comment by dirk-thomas** [comment] 2013-07-05 17:21
Please do not fill the same issue multiple times. Closing duplicate of #21

**Closed as completed by dirk-thomas** 2013-07-05 17:21 UTC
Labels: duplicate
