### ISSUE TITLE
rosbash: zsh auto-completion issues

### ISSUE THREAD

**Issue by jbohren** [ros/ros#48] opened 2014-03-27 13:22 UTC
- [x] roslaunch: good
- [ ] rosrun: 
  - package auto-completes
  - executable **does not autocomplete for installed executables**
  - executable **autocompletes git hooks in addition to executables**
- [x] roscd: good
- [ ] rostopic pub:
  - topic name auto-completes
  - message type auto-completes (but it would be nice if this was determined automatically if the topic is already subscribed to)
  - message cmd-line YAML **does not autocomplete**

**Comment by dirk-thomas** [comment] 2014-03-27 16:11
Thanks for summarizing the state that detailed. Please consider to provide patches for improved `zsh` support. Since most people are only using `bash` this won't be high on the priority list.

**Comment by dirk-thomas** [comment] 2014-05-02 17:27
@wjwwood since you use zsh on Mac you might want to take a look at this at some point.

**Comment by trainman419** [comment] 2014-05-06 20:14
Tab-completion for installed executables in rosrun should be fixed in https://github.com/ros/ros/commit/bba94288c13e8c0d0b433ccadfa4b12249838659

**Comment by bajo** [comment] 2014-08-04 07:20
@jbohren Could you shed a little light on the issue that rosrun is not able to autocomplete installed executables? Can you try a current version and report if this still is a problem, because I think @trainman419 resolved this in https://github.com/ros/ros/commit/bba94288c13e8c0d0b433ccadfa4b12249838659 

If this is the case you could update and close this issue as this and the rostopic autocompletion  https://github.com/ros/ros/commit/dc18b0042afbcfaf9d13d41ca2d15e3f96934839 are working now.

Thanks.

**Comment by dirk-thomas** [comment] 2014-10-22 00:11
It seems to also work for me. Therefore closing the ticket for now. If there is more information about what is not working please feel free to comment and it can be reopened.

**Closed as completed by dirk-thomas** 2014-10-22 00:11 UTC
Labels: enhancement

**Comment by furushchev** [comment] 2015-09-15 01:31
Was this issue solved? I still doubt it does work on zsh when `rosrun` and `rostopic`.

**Comment by bajo** [comment] 2015-09-15 06:17
@furushchev Can you describe what exactly is not working for you?
I just tested it with rostopic pub <Tab> <Tab> <Tab> and it completed it to 
rostopic pub /rosout rosgraph_msgs/Log "header:
  seq: 0
  stamp: {secs: 0, nsecs: 0}
  frame_id: ''
level: 0
name: ''
msg: ''
file: ''
function: ''
line: 0
topics: ['']"

rosrun rv<Tab> <Tab> autocompletes to rosrun rviz rviz. Just as expected.
The roszsh file i am using on Ubuntu 14.04 with indigo is from commit 56eb5175e65109a44a4c1cf716571b3ac377af17

**Comment by edobez** [comment] 2015-09-16 16:21
Zsh completion with rosrun is still not working for me on Ubuntu 14.04/Indigo.
The completion could find the package, but throws an error when trying to complete the executable.

This is what comes out when I try to complete view_frames from tf package:
`find: /opt/ros/indigo/lib/tf\n/opt/ros/indigo/lib/tf': No such file or directory`

**Comment by dirk-thomas** [comment] 2015-09-16 16:36
@edobez I think what you are seeing is #83 which will be addressed with an upcoming release.

**Comment by bajo** [comment] 2015-09-16 17:25
@edobez @dirk-thomas At first I could not reproduce this as well, but i think I now know how I can get it to show at least for my setup. I work on a few different projects which are in their own catkin workspaces. In my .zshrc I only source /opt/ros/indigo/setup.zsh . Whenever I need a certain project I source the projects devel/setup.zsh as well. 

When I start a terminal the autocompletion works fine and just as expected. As soon as I source one of my projects setup.zsh the same error as @edobez reported showed up. 
I think the issue is that in function _roscomplete_search_dir we execute catkin_package_libexec_dir=`catkin_find --without-underlays --libexec ${pkg} 2> /dev/null` which will return /opt/ros/indigo/lib/tf\n/opt/ros/indigo/lib/tf in the case of the tf package. This is of course no valid path for the following find command which is exactly the reported error. 

As the catkin_find command has the nice switch --first-only that can take care of this issue we can solve this quite easy by adding this to the catkin_find command. 
Ah, just saw that this is already in the branch for jade, so never mind.  ;-)

**Comment by furushchev** [comment] 2015-10-02 10:54
@bajo Sorry for very late response. I chekced on hydro / ubuntu 12.04. (rosbash version is 0.10.11)
So is hydro already deprecated?

**Comment by dirk-thomas** [comment] 2015-10-02 10:56
Hydro has been EOL for quite a while (May 2015) and the build farm has been decommissioned by now. So there will for sure be no released into Hydro anymore.
