### ISSUE TITLE
rossrv md5 and gendeps --md5 differs in groovy

### ISSUE THREAD

**Issue by HiroyukiMikita** [ros/ros#18] opened 2013-06-20 12:36 UTC
HI,

the reuslt of rossrv md5 and gendeps --md5 differs in groovy, which produces same value in fuerte.

$ rossrv md5 object_manipulation_msgs/GraspPlanning
01a11c1cdea613dd8705f368e1dc93dc
$ rosrun roslib gendeps --md5 `rospack find object_manipulation_msgs`/srv/GraspPlanning.srv
db313b83432c8e8e7bc948bf53911e92

**Comment by dirk-thomas** [comment] 2013-06-20 16:41
I tried to reproduce it with two other services (`std_srvs/Empty` and `roscpp/SetLoggerLevel`) and both commands return the same hash.

Can you please provide more information:

```
rossrv show object_manipulation_msgs/GraspPlanning
rospack find object_manipulation_msgs
cat `rospack find object_manipulation_msgs`/srv/GraspPlanning.srv
```

**Comment by HiroyukiMikita** [comment] 2013-06-21 00:02
I found that this problem occurred with `object_manipulation_msgs/GraspPlanning` and `tabletop_object_detector/TabletopDetection` .
Not with all services.

<pre>
$ rosversion roslib
1.9.45
$ rospack find object_manipulation_msgs
/opt/ros/groovy/stacks/object_manipulation/object_manipulation_msgs
$ rosversion object_manipulation
0.7.2
$ rossrv show object_manipulation_msgs/GraspPlanning
string arm_name
object_manipulation_msgs/GraspableObject target
  string reference_frame_id
  household_objects_database_msgs/DatabaseModelPose[] potential_models
    int32 model_id
    object_recognition_msgs/ObjectType type
      string key
      string db
    geometry_msgs/PoseStamped pose
      std_msgs/Header header
        uint32 seq
        time stamp
        string frame_id
      geometry_msgs/Pose pose
        geometry_msgs/Point position
          float64 x
          float64 y
          float64 z
        geometry_msgs/Quaternion orientation
          float64 x
          float64 y
          float64 z
          float64 w
    float32 confidence
    string detector_name
  sensor_msgs/PointCloud cluster
    std_msgs/Header header
      uint32 seq
      time stamp
      string frame_id
    geometry_msgs/Point32[] points
      float32 x
      float32 y
      float32 z
    sensor_msgs/ChannelFloat32[] channels
      string name
      float32[] values
  object_manipulation_msgs/SceneRegion region
    sensor_msgs/PointCloud2 cloud
      std_msgs/Header header
        uint32 seq
        time stamp
        string frame_id
      uint32 height
      uint32 width
      sensor_msgs/PointField[] fields
        uint8 INT8=1
        uint8 UINT8=2
        uint8 INT16=3
        uint8 UINT16=4
        uint8 INT32=5
        uint8 UINT32=6
        uint8 FLOAT32=7
        uint8 FLOAT64=8
        string name
        uint32 offset
        uint8 datatype
        uint32 count
      bool is_bigendian
      uint32 point_step
      uint32 row_step
      uint8[] data
      bool is_dense
    int32[] mask
    sensor_msgs/Image image
      std_msgs/Header header
        uint32 seq
        time stamp
        string frame_id
      uint32 height
      uint32 width
      string encoding
      uint8 is_bigendian
      uint32 step
      uint8[] data
    sensor_msgs/Image disparity_image
      std_msgs/Header header
        uint32 seq
        time stamp
        string frame_id
      uint32 height
      uint32 width
      string encoding
      uint8 is_bigendian
      uint32 step
      uint8[] data
    sensor_msgs/CameraInfo cam_info
      std_msgs/Header header
        uint32 seq
        time stamp
        string frame_id
      uint32 height
      uint32 width
      string distortion_model
      float64[] D
      float64[9] K
      float64[9] R
      float64[12] P
      uint32 binning_x
      uint32 binning_y
      sensor_msgs/RegionOfInterest roi
        uint32 x_offset
        uint32 y_offset
        uint32 height
        uint32 width
        bool do_rectify
    geometry_msgs/PoseStamped roi_box_pose
      std_msgs/Header header
        uint32 seq
        time stamp
        string frame_id
      geometry_msgs/Pose pose
        geometry_msgs/Point position
          float64 x
          float64 y
          float64 z
        geometry_msgs/Quaternion orientation
          float64 x
          float64 y
          float64 z
          float64 w
    geometry_msgs/Vector3 roi_box_dims
      float64 x
      float64 y
      float64 z
  string collision_name
string collision_object_name
string collision_support_surface_name
object_manipulation_msgs/Grasp[] grasps_to_evaluate
  sensor_msgs/JointState pre_grasp_posture
    std_msgs/Header header
      uint32 seq
      time stamp
      string frame_id
    string[] name
    float64[] position
    float64[] velocity
    float64[] effort
  sensor_msgs/JointState grasp_posture
    std_msgs/Header header
      uint32 seq
      time stamp
      string frame_id
    string[] name
    float64[] position
    float64[] velocity
    float64[] effort
  geometry_msgs/Pose grasp_pose
    geometry_msgs/Point position
      float64 x
      float64 y
      float64 z
    geometry_msgs/Quaternion orientation
      float64 x
      float64 y
      float64 z
      float64 w
  float64 success_probability
  bool cluster_rep
  float32 desired_approach_distance
  float32 min_approach_distance
  object_manipulation_msgs/GraspableObject[] moved_obstacles
    string reference_frame_id
    household_objects_database_msgs/DatabaseModelPose[] potential_models
      int32 model_id
      object_recognition_msgs/ObjectType type
        string key
        string db
      geometry_msgs/PoseStamped pose
        std_msgs/Header header
          uint32 seq
          time stamp
          string frame_id
        geometry_msgs/Pose pose
          geometry_msgs/Point position
            float64 x
            float64 y
            float64 z
          geometry_msgs/Quaternion orientation
            float64 x
            float64 y
            float64 z
            float64 w
      float32 confidence
      string detector_name
    sensor_msgs/PointCloud cluster
      std_msgs/Header header
        uint32 seq
        time stamp
        string frame_id
      geometry_msgs/Point32[] points
        float32 x
        float32 y
        float32 z
      sensor_msgs/ChannelFloat32[] channels
        string name
        float32[] values
    object_manipulation_msgs/SceneRegion region
      sensor_msgs/PointCloud2 cloud
        std_msgs/Header header
          uint32 seq
          time stamp
          string frame_id
        uint32 height
        uint32 width
        sensor_msgs/PointField[] fields
          uint8 INT8=1
          uint8 UINT8=2
          uint8 INT16=3
          uint8 UINT16=4
          uint8 INT32=5
          uint8 UINT32=6
          uint8 FLOAT32=7
          uint8 FLOAT64=8
          string name
          uint32 offset
          uint8 datatype
          uint32 count
        bool is_bigendian
        uint32 point_step
        uint32 row_step
        uint8[] data
        bool is_dense
      int32[] mask
      sensor_msgs/Image image
        std_msgs/Header header
          uint32 seq
          time stamp
          string frame_id
        uint32 height
        uint32 width
        string encoding
        uint8 is_bigendian
        uint32 step
        uint8[] data
      sensor_msgs/Image disparity_image
        std_msgs/Header header
          uint32 seq
          time stamp
          string frame_id
        uint32 height
        uint32 width
        string encoding
        uint8 is_bigendian
        uint32 step
        uint8[] data
      sensor_msgs/CameraInfo cam_info
        std_msgs/Header header
          uint32 seq
          time stamp
          string frame_id
        uint32 height
        uint32 width
        string distortion_model
        float64[] D
        float64[9] K
        float64[9] R
        float64[12] P
        uint32 binning_x
        uint32 binning_y
        sensor_msgs/RegionOfInterest roi
          uint32 x_offset
          uint32 y_offset
          uint32 height
          uint32 width
          bool do_rectify
      geometry_msgs/PoseStamped roi_box_pose
        std_msgs/Header header
          uint32 seq
          time stamp
          string frame_id
        geometry_msgs/Pose pose
          geometry_msgs/Point position
            float64 x
            float64 y
            float64 z
          geometry_msgs/Quaternion orientation
            float64 x
            float64 y
            float64 z
            float64 w
      geometry_msgs/Vector3 roi_box_dims
        float64 x
        float64 y
        float64 z
    string collision_name
object_manipulation_msgs/GraspableObject[] movable_obstacles
  string reference_frame_id
  household_objects_database_msgs/DatabaseModelPose[] potential_models
    int32 model_id
    object_recognition_msgs/ObjectType type
      string key
      string db
    geometry_msgs/PoseStamped pose
      std_msgs/Header header
        uint32 seq
        time stamp
        string frame_id
      geometry_msgs/Pose pose
        geometry_msgs/Point position
          float64 x
          float64 y
          float64 z
        geometry_msgs/Quaternion orientation
          float64 x
          float64 y
          float64 z
          float64 w
    float32 confidence
    string detector_name
  sensor_msgs/PointCloud cluster
    std_msgs/Header header
      uint32 seq
      time stamp
      string frame_id
    geometry_msgs/Point32[] points
      float32 x
      float32 y
      float32 z
    sensor_msgs/ChannelFloat32[] channels
      string name
      float32[] values
  object_manipulation_msgs/SceneRegion region
    sensor_msgs/PointCloud2 cloud
      std_msgs/Header header
        uint32 seq
        time stamp
        string frame_id
      uint32 height
      uint32 width
      sensor_msgs/PointField[] fields
        uint8 INT8=1
        uint8 UINT8=2
        uint8 INT16=3
        uint8 UINT16=4
        uint8 INT32=5
        uint8 UINT32=6
        uint8 FLOAT32=7
        uint8 FLOAT64=8
        string name
        uint32 offset
        uint8 datatype
        uint32 count
      bool is_bigendian
      uint32 point_step
      uint32 row_step
      uint8[] data
      bool is_dense
    int32[] mask
    sensor_msgs/Image image
      std_msgs/Header header
        uint32 seq
        time stamp
        string frame_id
      uint32 height
      uint32 width
      string encoding
      uint8 is_bigendian
      uint32 step
      uint8[] data
    sensor_msgs/Image disparity_image
      std_msgs/Header header
        uint32 seq
        time stamp
        string frame_id
      uint32 height
      uint32 width
      string encoding
      uint8 is_bigendian
      uint32 step
      uint8[] data
    sensor_msgs/CameraInfo cam_info
      std_msgs/Header header
        uint32 seq
        time stamp
        string frame_id
      uint32 height
      uint32 width
      string distortion_model
      float64[] D
      float64[9] K
      float64[9] R
      float64[12] P
      uint32 binning_x
      uint32 binning_y
      sensor_msgs/RegionOfInterest roi
        uint32 x_offset
        uint32 y_offset
        uint32 height
        uint32 width
        bool do_rectify
    geometry_msgs/PoseStamped roi_box_pose
      std_msgs/Header header
        uint32 seq
        time stamp
        string frame_id
      geometry_msgs/Pose pose
        geometry_msgs/Point position
          float64 x
          float64 y
          float64 z
        geometry_msgs/Quaternion orientation
          float64 x
          float64 y
          float64 z
          float64 w
    geometry_msgs/Vector3 roi_box_dims
      float64 x
      float64 y
      float64 z
  string collision_name
---
object_manipulation_msgs/Grasp[] grasps
  sensor_msgs/JointState pre_grasp_posture
    std_msgs/Header header
      uint32 seq
      time stamp
      string frame_id
    string[] name
    float64[] position
    float64[] velocity
    float64[] effort
  sensor_msgs/JointState grasp_posture
    std_msgs/Header header
      uint32 seq
      time stamp
      string frame_id
    string[] name
    float64[] position
    float64[] velocity
    float64[] effort
  geometry_msgs/Pose grasp_pose
    geometry_msgs/Point position
      float64 x
      float64 y
      float64 z
    geometry_msgs/Quaternion orientation
      float64 x
      float64 y
      float64 z
      float64 w
  float64 success_probability
  bool cluster_rep
  float32 desired_approach_distance
  float32 min_approach_distance
  object_manipulation_msgs/GraspableObject[] moved_obstacles
    string reference_frame_id
    household_objects_database_msgs/DatabaseModelPose[] potential_models
      int32 model_id
      object_recognition_msgs/ObjectType type
        string key
        string db
      geometry_msgs/PoseStamped pose
        std_msgs/Header header
          uint32 seq
          time stamp
          string frame_id
        geometry_msgs/Pose pose
          geometry_msgs/Point position
            float64 x
            float64 y
            float64 z
          geometry_msgs/Quaternion orientation
            float64 x
            float64 y
            float64 z
            float64 w
      float32 confidence
      string detector_name
    sensor_msgs/PointCloud cluster
      std_msgs/Header header
        uint32 seq
        time stamp
        string frame_id
      geometry_msgs/Point32[] points
        float32 x
        float32 y
        float32 z
      sensor_msgs/ChannelFloat32[] channels
        string name
        float32[] values
    object_manipulation_msgs/SceneRegion region
      sensor_msgs/PointCloud2 cloud
        std_msgs/Header header
          uint32 seq
          time stamp
          string frame_id
        uint32 height
        uint32 width
        sensor_msgs/PointField[] fields
          uint8 INT8=1
          uint8 UINT8=2
          uint8 INT16=3
          uint8 UINT16=4
          uint8 INT32=5
          uint8 UINT32=6
          uint8 FLOAT32=7
          uint8 FLOAT64=8
          string name
          uint32 offset
          uint8 datatype
          uint32 count
        bool is_bigendian
        uint32 point_step
        uint32 row_step
        uint8[] data
        bool is_dense
      int32[] mask
      sensor_msgs/Image image
        std_msgs/Header header
          uint32 seq
          time stamp
          string frame_id
        uint32 height
        uint32 width
        string encoding
        uint8 is_bigendian
        uint32 step
        uint8[] data
      sensor_msgs/Image disparity_image
        std_msgs/Header header
          uint32 seq
          time stamp
          string frame_id
        uint32 height
        uint32 width
        string encoding
        uint8 is_bigendian
        uint32 step
        uint8[] data
      sensor_msgs/CameraInfo cam_info
        std_msgs/Header header
          uint32 seq
          time stamp
          string frame_id
        uint32 height
        uint32 width
        string distortion_model
        float64[] D
        float64[9] K
        float64[9] R
        float64[12] P
        uint32 binning_x
        uint32 binning_y
        sensor_msgs/RegionOfInterest roi
          uint32 x_offset
          uint32 y_offset
          uint32 height
          uint32 width
          bool do_rectify
      geometry_msgs/PoseStamped roi_box_pose
        std_msgs/Header header
          uint32 seq
          time stamp
          string frame_id
        geometry_msgs/Pose pose
          geometry_msgs/Point position
            float64 x
            float64 y
            float64 z
          geometry_msgs/Quaternion orientation
            float64 x
            float64 y
            float64 z
            float64 w
      geometry_msgs/Vector3 roi_box_dims
        float64 x
        float64 y
        float64 z
    string collision_name
object_manipulation_msgs/GraspPlanningErrorCode error_code
  int32 SUCCESS=0
  int32 TF_ERROR=1
  int32 OTHER_ERROR=2
  int32 value
$ cat `rospack find object_manipulation_msgs`/srv/GraspPlanning.srv
# Requests that grasp planning be performed on the object to be grasped
# returns a list of grasps to be tested and executed
# the arm being used
string arm_name
# the object to be grasped
GraspableObject target
# the name that the target object has in the collision environment
# can be left empty if no name is available
string collision_object_name
# the name that the support surface (e.g. table) has in the collision map
# can be left empty if no name is available
string collision_support_surface_name
# an optional list of grasps to be evaluated by the planner
Grasp[] grasps_to_evaluate
# an optional list of obstacles that we have semantic information about
# and that can be moved in the course of grasping
GraspableObject[] movable_obstacles
---
# the list of planned grasps
Grasp[] grasps
# whether an error occurred
GraspPlanningErrorCode error_code
</pre>

**Comment by dirk-thomas** [comment] 2013-06-21 18:17
I can't reproduce your case anymore since as far as I can see the current version of object_manipulation (0.7.3) seems to not have that specific service file anymore.

Also in your comment it clearly shows that the content of the two files which you compute the hash for are completely different. So it is no surprise that the hash is not equal.

Without any further information I can't narrow down what the issue is with your local setup but it is pretty sure not a bug in the hash computation. Therefore I am closing this ticket - you might want to post a question on answers.ros.org.

**Closed as completed by dirk-thomas** 2013-06-21 18:17 UTC
Labels: invalid
