### ISSUE TITLE
rosrun doesn't handle file permission correctly

### ISSUE THREAD

**Issue by SvenAlbrecht** [ros/ros#40] opened 2013-10-15 14:27 UTC
In hydro 'rosrun' ignores all executables, if you're not using 'darwin', which do not have all executable bits set.
This is due to line 38 in the 'rosrun' script, where the permission mask is set for the subsequent 'find' command. I believe 'rosrun' should be able to execute a file for me, if I am the owner of said file and have executable rights without giving executable rights to group members or other users.
The behavior can be reproduced easily if you've an executable which can be executed via 'rosrun' at the moment and remove for exemple the group executable rights via 'chmod'.

**Comment by dirk-thomas** [comment] 2013-10-15 17:24
That is a regression from https://github.com/ros/ros/pull/37. I don't know how I screwed up that one. The previous discussion #33 clearly came to the conclusion to use `/111` on non-darwin systems. Will commit and release a fix soon.

**Comment by dirk-thomas** [comment] 2013-10-15 17:29
Fixed in b6b49a28b9970e3f7632fd75f352aa928019bff7 and d6d54b8f5cc43eab50b14cddca04eb844fa8bab1.

**Closed as completed by dirk-thomas** 2013-10-15 17:29 UTC
Labels: bug

**Comment by SvenAlbrecht** [comment] 2013-10-16 13:19
thx for the quick fix

**Comment by dodsonmg** [comment] 2020-01-20 14:45
This is pretty old now, but since @dirk-thomas seems to respond quickly to all my questions:

This issue with `find` is also applicable to FreeBSD (not surprising, given the common ancestry with Darwin).

I verified by modifying `rosbash` and `rosrun` source files to use `+111` instead of `/111` for `$(uname) == FreeBSD`, and it works.

Previously, when I would attempt to use `rosrun`, I was getting an error associated with `/111`, and then it would tell me that it had found a file named [executable I was trying to run] but that it wasn't an executable.

**Comment by tfoote** [comment] 2020-01-22 02:39
@dodsonmg Since this is a closed ticket it's unlikely to get reviewed. Please open a new one or even better a PR otherwise no one is likely to follow up. And as we don't have FreeBSD systems to test on it's even less likely.

**Comment by dodsonmg** [comment] 2020-01-22 11:44
I can open a new one.  I actually left it here as a breadcrumb for people searching in the future.

I am planning on a PR, though.
