### ISSUE TITLE
MD5sum generation ignores array qualities of sub-message fields

### ISSUE THREAD

**Issue by furtypajohn** [ros/ros#178] opened 2018-05-01 02:43 UTC
In the roslib.gentools, module the [compute_md5_text function line 156](https://github.com/ros/ros/blob/kinetic-devel/core/roslib/src/roslib/gentools.py#L156) fails to handle whether a message field is an array or not. This can result in the same MD5 being generated for messages that are different. For example, given the following message definition:

`std_msgs/UInt8 data`

and, let's say this message changes to the following:

`std_msgs/UInt8[] data`

This will result in the same MD5 being generated despite the fact that data has been changed to an array in the second form of the message. Any code that relies on the MD5 to detect changes to messages would then not be able to detect these changes.

The error is on line [156 of gentools.py](https://github.com/ros/ros/blob/kinetic-devel/core/roslib/src/roslib/gentools.py#L156), which reads:

`buff.write("%s %s\n"%(sub_md5, name))`

This incorporates the MD5 hash of the sub-message type and the name of its field but fails to take into account whether the field (that is a ROS message type) is an array. So the text used to generate the MD5 doesn't include this information.

Note: gentools properly takes into account (see [line 141](https://github.com/ros/ros/blob/kinetic-devel/core/roslib/src/roslib/gentools.py#L141)) the array-ness for basic types:

`uff.write("%s %s\n"%(type_, name))`

As the type_ variable includes the information on whether the field is an array. Thus, MD5s are generated correctly enough to detect changes to fields that are basic types not not fields that are themselves ROS messages.

**Comment by dirk-thomas** [comment] 2018-05-01 04:14
This looks like a duplicate of ros/genmsg#50. Please see the comments there why that behavior can't be fixed with breaking compatibility.

**Closed as completed** 2019-08-12 18:50 UTC
Labels: duplicate
